# Run this workflow every time a new commit pushed to your repository
stages:   
  - format       # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  DEPS_DIR: $CI_PROJECT_DIR/deps
  HUNTER_ROOT: $CI_PROJECT_DIR/hunter
  
       
clang-format-job:
    stage: format
    variables:
      GIT_CHECKOUT: "true"
    tags: 
      - linux
    script:
      - echo "Checking if the code is well formated"
      - clang-format --version
      - echo "Checking developers folder"
      - $CI_PROJECT_DIR/scripts/ci/run-clang-format.py -r --clang-format-executable clang-format --color always $CI_PROJECT_DIR/developers/
      - echo "Checking include folder"
      - $CI_PROJECT_DIR/scripts/ci/run-clang-format.py -r --clang-format-executable clang-format --color always $CI_PROJECT_DIR/include/
      - echo "Checking lecturecodes folder"
      - $CI_PROJECT_DIR/scripts/ci/run-clang-format.py -r --clang-format-executable clang-format --color always $CI_PROJECT_DIR/lecturecodes/

# compilation on macos
compile-developers-job-mac:
    stage: build
    variables:
      COMPILER: "clang++"
      BUILD_TYPE: "Release"
      CXXFLAGS: "-Werror=#warnings"
      GIT_CHECKOUT: "true"
    tags:
        - mac
    script:
       - mkdir -p $CI_PROJECT_DIR/build_mac #-p builds if not there and does nothing otherwise

       - cd $CI_PROJECT_DIR/build_mac
       - export CXX=$COMPILER
       - echo $CXX
       - cmake .. -DHOMEWORKS=OFF -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS_DEBUG="-g0" -DHUNTER_CONFIGURATION_TYPES=$BUILD_TYPE -Wdev

       - echo "Building developer folder"
       - cd developers
       - make -j 4
    artifacts:
      paths:
        - build_mac/*
      expire_in: 1 days

compile-developers-job-linux:
    stage: build
    variables:
      COMPILER: "g++"
      BUILD_TYPE: "Release"
      CXXFLAGS: "-Werror=cpp"
      GIT_CHECKOUT: "true"

    tags:
        - linux
    script:
       - mkdir -p $CI_PROJECT_DIR/build_linux #-p builds if not there and does nothing otherwise

       - cd $CI_PROJECT_DIR/build_linux
       - export CXX=$COMPILER
       - echo $CXX

       - cmake .. -DHOMEWORKS=OFF -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS_DEBUG="-g0" -DHUNTER_CONFIGURATION_TYPES=$BUILD_TYPE -Wdev
       - echo "Building developer folder"
       - cd developers
       - make -j 4
    artifacts:
      paths:
        - build_linux/*
      expire_in: 1 days

test-developer-job-mac:
  stage: test
  tags:
    - mac
  dependencies:
    - compile-developers-job-mac
  script:
       - echo "Testing developer folder master solutions"
       - cd $CI_PROJECT_DIR/build_mac
       - echo "Testing developer folder master solutions"
       - $CI_PROJECT_DIR/scripts/ci/test_developers.sh
       - echo "Testing lecturecodes"
       - $CI_PROJECT_DIR/scripts/ci/run_lecturecodes.sh

test-developer-job-linux:
  stage: test
  tags:
    - linux
  dependencies:
    - compile-developers-job-linux
  script:
       - echo "Testing developer folder master solutions"
       - cd $CI_PROJECT_DIR/build_linux
       - echo "Testing developer folder master solutions"
       - $CI_PROJECT_DIR/scripts/ci/test_developers.sh
       - echo "Testing lecturecodes"
       - $CI_PROJECT_DIR/scripts/ci/run_lecturecodes.sh