# Run this workflow every time a new commit pushed to your repository
stages:   
  - format       # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  DEPS_DIR: $CI_PROJECT_DIR/deps
  HUNTER_ROOT: $CI_PROJECT_DIR/hunter
  
       
clang-format-job:
    stage: format
    variables:
      GIT_CHECKOUT: "true"
    tags: 
      - linux
    script:
      - echo "Checking if the code is well formated"
      - clang-format --version
      - $CI_PROJECT_DIR/scripts/ci/run-clang-format.py -r --clang-format-executable clang-format --color always $CI_PROJECT_DIR/developers/

# compilation on macos
compile-developers-release-job-mac:
    stage: build
    variables:
      COMPILER: "clang++"
      BUILD_TYPE: "Release"
      CXXFLAGS: "-Werror=#warnings"
      GIT_CHECKOUT: "true"
    tags:
        - mac
    script:
       
       - mkdir $CI_PROJECT_DIR/build
       - cd $CI_PROJECT_DIR/build 
       - export CXX=$COMPILER
       - echo $CXX
       - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS_DEBUG="-g0" -DHUNTER_CONFIGURATION_TYPES=$BUILD_TYPE -Wdev
       - echo "Building developer folder"
       - cd developers
       - make -j 4
       - cd $CI_PROJECT_DIR/build 
       - echo "Testing developer folder master solutions"
       - chmod +x $CI_PROJECT_DIR/scripts/ci/test_developers.sh
       - $CI_PROJECT_DIR/scripts/ci/test_developers.sh
    # Ideally testing and building are separated jobs, but the builded folders seem to be to large to be uploaded,
    # in the future the scripts may be able to be separated, for now testing and building will be done in one job
    #artifacts:
     # paths :
      #  - build/developers

compile-developers-debug-job-linux:
    stage: build
    variables:
      COMPILER: "g++"
      BUILD_TYPE: "Debug"
      CXXFLAGS: "--Werror=cpp"
      GIT_CHECKOUT: "true"

    tags:
        - linux
    script:
       - echo Create a build folder
       - mkdir $CI_PROJECT_DIR/build
       - cd $CI_PROJECT_DIR/build 
       - export CXX=$COMPILER
       - echo $CXX
       - set(CMAKE_CXX_COMPILER_WORKS 1) # Skips checking the compiler
       - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS_DEBUG="-g0" -DHUNTER_CONFIGURATION_TYPES=$BUILD_TYPE -Wdev
       - echo "Building developer folder"
       - cd developers
       - make -j 4

#TDOO: Run these commands also for linux
test-developer-job:
  stage: test
  tags:
    - mac
  script:
    - echo "Testing developer folder"
    - echo "As of right now testing is done while building"

