# Run this workflow every time a new commit pushed to your repository
stages:   
  - format       # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  DEPS_DIR: $CI_PROJECT_DIR/deps
  HUNTER_ROOT: $CI_PROJECT_DIR/hunter
  
       
clang-format-job:
    stage: format
    variables:
      GIT_CHECKOUT: "true"
    tags: 
      - linux
    script:
      - echo "Checking if the code is well formated"
      - clang-format --version
      - $CI_PROJECT_DIR/scripts/ci/run-clang-format.py -r --clang-format-executable clang-format --color always $CI_PROJECT_DIR/developers/

# compilation on macos
compile-developers-release-job-mac:
    stage: build
    variables:
      COMPILER: "clang++"
      BUILD_TYPE: "Release"
      CXXFLAGS: "-Werror=#warnings"
      GIT_CHECKOUT: "true"
    tags:
        - mac
    script:
       
       - mkdir $CI_PROJECT_DIR/build_release
       - cd $CI_PROJECT_DIR/build_release
       - export CXX=$COMPILER
       - echo $CXX
       - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS_DEBUG="-g0" -DHUNTER_CONFIGURATION_TYPES=$BUILD_TYPE -Wdev

       - echo "Building developer folder"
       - cd developers
       - make -j 4

    cache:
      key : developers-release-mac
      paths : 
        - $CI_PROJECT_DIR/build_release/developers/
       

compile-developers-debug-job-linux:
    stage: build
    variables:
      COMPILER: "g++"
      BUILD_TYPE: "Debug"
      CXXFLAGS: "-Werror=cpp"
      GIT_CHECKOUT: "true"

    tags:
        - linux
    script:
       - echo Create a build folder
       - mkdir $CI_PROJECT_DIR/build_debug
       - cd $CI_PROJECT_DIR/build_debug
       - export CXX=$COMPILER
       - echo $CXX

       - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS_DEBUG="-g0" -DHUNTER_CONFIGURATION_TYPES=$BUILD_TYPE -Wdev
       - echo "Building developer folder"
       - cd developers
       - make -j 4
    cache:
      key : developers-debug-linux
      paths : 
        - $CI_PROJECT_DIR/build_debug/developers/

test-developer-release-job-mac:
  stage: test
  tags:
    - mac
  script:
       - echo "Testing developer folder master solutions"
       - cd $CI_PROJECT_DIR/build_release
       - chmod +x $CI_PROJECT_DIR/scripts/ci/test_developers.sh
       - $CI_PROJECT_DIR/scripts/ci/test_developers.sh
  cache:
    key : developers-release-mac
    paths : 
      - $CI_PROJECT_DIR/build_release/developers/

test-developer-debug-job-linux:
  stage: test
  tags:
    - linux
  script:
       - echo "Testing developer folder master solutions"
       - cd $CI_PROJECT_DIR/build_debug 
       - chmod +x $CI_PROJECT_DIR/scripts/ci/test_developers.sh
       - $CI_PROJECT_DIR/scripts/ci/test_developers.sh
  cache:
    key : developers-debug-linux
    paths : 
      - $CI_PROJECT_DIR/build_debug/developers/
