# Run this workflow every time a new commit pushed to your repository
stages:   
  - format       # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  DEPS_DIR: $CI_PROJECT_DIR/deps
  HUNTER_ROOT: $CI_PROJECT_DIR/hunter
  
       
clang-format-job:
    stage: format
    variables:
      GIT_CHECKOUT: "true"
    tags: 
      - macos
    script:
      - echo "Checking if the code is well formated"

      - clang-format --version
      - $CI_PROJECT_DIR/scripts/ci/run-clang-format.py -r --clang-format-executable clang-format --color always $CI_PROJECT_DIR/developers/

# compilation on macos
compile-developers-release-job:
    stage: build
    variables:
      COMPILER: "clang++"
      BUILD_TYPE: "Release"
      CXXFLAGS: "-Werror=#warnings"
      GIT_CHECKOUT: "true"
    tags:
        - macos
    script:
       
       - mkdir $CI_PROJECT_DIR/build
       - cd $CI_PROJECT_DIR/build 
       - cmake .. 
       - echo "Building developer folder"
       - cd developers
       - make -j8
       - cd $CI_PROJECT_DIR/build 
       - echo "Testing developer folder master solutions"
       - $CI_PROJECT_DIR/scripts/ci/test_developers.sh
    # Ideally testing and building are separated jobs, but the builded folders seem to be to large to be uploaded,
    # in the future the scripts may be able to be separated, for now testing and building will be done in one job
    #artifacts:
     # paths :
      #  - build/developers

#TDOO: Run these commands also for linux
test-developer-job:
  stage: test
  tags:
    - macos
  script:
    - echo "Testing developer folder"
    - echo "As of right now testing is done while building"

